replicaCount: 1

#role: 
  #name: api-template
  #rules:
  #- apiGroups:
    #- batch
    #resources:
    #- jobs
    #verbs:
    #- create
    #- get
    #- list

serviceAccount:
  create: false
  #name: api-template

department: data-engineering
image:
  repository: 793999821937.dkr.ecr.ap-southeast-1.amazonaws.com/api-template
  tag: latest
  pullPolicy: Always
container:
  port: 8000
  healthCheckUrl: /heartbeat
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: "1"
  environments:
    - name: FLASK_DEBUG
      value: "0"
    # AWS X-RAY
    - name: AWS_XRAY_DAEMON_ADDRESS
      value: udp:xray-service.default:2000 tcp:xray-service.default:2000 

    - name: AWS_XRAY_CONTEXT_MISSING
      value: LOG_ERROR

    - name: XRAY_ENABLED
      value: "True"

    - name: XRAY_INSPECT_QUERY
      value: "False"

    - name: AWS_XRAY_SDK_ENABLED
      value: "True"

    # Environment
    - name: FLASK_ENV
      value: development

    # Entry point
    - name: FLASK_APP
      value: main.py

    # Flask port, default port is 5000
    - name: FLASK_RUN_PORT
      value: "8000"

    # Logging level
    - name: LOG_LEVEL
      value: INFO

    - name: JWT_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: api-template-credentials
          key: jwt_secret_key

    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: api-template-credentials
          key: database_password
      
    - name: DATABASE_URI
      valueFrom:
        configMapKeyRef:
          name: api-template-configmap
          key: database_uri

    - name: SQLALCHEMY_POOL_RECYCLE
      value: "280"

    - name: PRODUCER_TOPICS
      value: "api-template-queue"

    - name: PRODUCER_TYPE
      value: "InMemoryProducer"

    - name: TOPIC_CONSUMERS
      value: "SampleConsumer:InMemoryConsumer"

    - name: TOPIC_INTERVAL
      value: "2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=data-engineering,app=api-template
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:793999821937:certificate/4f1511e7-6f45-4462-a248-5327ac36403c
    alb.ingress.kubernetes.io/healthcheck-path: /heartbeat
    alb.ingress.kubernetes.io/success-codes: 200-301
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '8'
    alb.ingress.kubernetes.io/subnets: subnet-05e7f58e4756ba096,subnet-057ece57a3546225d,subnet-0f0b8bd265f8eeea4
  hosts:
  - host: test.dev.data.rea-asia.com
    paths:
    - path: /*
      servicePort: 80
      serviceName: api-template-service


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
- name: api-template-credentials
  data:
    database_password: Ymd1a2VlSHJKcjI0ZXpzckxXS3o= #base64 encoded
    jwt_secret_key: U2VDcmVUS2V5 #base64 encoded

#secretFiles:
  #- name: location-cms-environment
    #data:
      #- name: .env
        #path : secrets/.env

configMap:
  name: api-template-configmap
  data:
    database_uri: mysql+pymysql://dbadmin:bgukeeHrJr24ezsrLWKz@ca2zergwylextf.csypt18aokzy.ap-southeast-1.rds.amazonaws.com:3306/commonsDB?connect_timeout=60
