replicaCount: 1

#role: 
  #name: api-template
  #rules:
  #- apiGroups:
    #- batch
    #resources:
    #- jobs
    #verbs:
    #- create
    #- get
    #- list

serviceAccount:
  create: false
  #name: api-template

department: data-engineering
image:
  repository: 958356994665.dkr.ecr.ap-southeast-1.amazonaws.com/api-template
  tag: latest
  pullPolicy: Always
container:
  port: 8000
  healthCheckUrl: /heartbeat
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: "1"
  #environments:
    #- name: WELCOME_TEXT
      #valueFrom:
        #configMapKeyRef:
          #name: index-page-configmap
          #key: welcome_text
    #- name: CLOUD_SQL_PASSWORD
      #valueFrom:
        #secretKeyRef:
          #name: cloud-sql-credentials
          #key: password
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: "Environment=staging,Team=data-engineering,app=api-template,Project=data-engineering,Business Unit=Shared,Contact=data.services@rea-group.com,Costcode=451"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:958356994665:certificate/36fc3a04-5b1a-443d-9a46-b75d720c8b79
    alb.ingress.kubernetes.io/healthcheck-path: /heartbeat
    alb.ingress.kubernetes.io/success-codes: 200-301
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '8'
    alb.ingress.kubernetes.io/subnets: subnet-0c4b92aa900565191,subnet-06b355f2e684f7d43,subnet-05f7e185b5eb3fa38
  hosts:
  - host: test.stg.data.rea-asia.com
    paths:
    - path: /*
      servicePort: 80
      serviceName: api-template-service

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
- name: api-template-credentials
  data:
    database_password: Ymd1a2VlSHJKcjI0ZXpzckxXS3o= #base64 encoded
    jwt_secret_key: U2VDcmVUS2V5 #base64 encoded

#secretFiles:
  #- name: location-cms-environment
    #data:
      #- name: .env
        #path : secrets/.env

configMap:
  name: api-template-configmap
  data:
    database_uri: mysql+pymysql://dbadmin:bgukeeHrJr24ezsrLWKz@ca2zergwylextf.csypt18aokzy.ap-southeast-1.rds.amazonaws.com:3306/commonsDB?connect_timeout=60
