# Default values for infra.

replicaCount: 1

department: data-engineering
image:
  repository: 958356994665.dkr.ecr.ap-southeast-1.amazonaws.com/api-template
  tag: latest
  pullPolicy: Always
#serviceAccountName: reporting-sa
container:
  port: 8000
  healthCheckUrl: /healthcheck
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: "1"
  #environments:
    #- name: WELCOME_TEXT
      #valueFrom:
        #configMapKeyRef:
          #name: index-page-configmap
          #key: welcome_text
    #- name: CLOUD_SQL_PASSWORD
      #valueFrom:
        #secretKeyRef:
          #name: cloud-sql-credentials
          #key: password
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=data-engineering,app=api-template
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:958356994665:certificate/36fc3a04-5b1a-443d-9a46-b75d720c8b79
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    alb.ingress.kubernetes.io/success-codes: 200-301
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '8'
  hosts:
    host: test.stg.data.rea-asia.com
    paths: /*
    port: 80

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#secrets:
  #name: cloud-sql-credentials
  #data:
    #password: eHhyRHFFSUsxMDN3eHRQdQ==
#configMap:
  #name: index-page-configmap
  #data:
    #welcome_text: kubernetes
    #cloud_sql_uri: mysql://root@10.114.193.5:3306/mysql
