steps:
  - label: "Running tests in development environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    artifact_paths:
      - "coverage.xml"
      - "py-test-report.xml"
      - "pylint-report.parseable"
  
  - wait

  - label: "Sonar scan :sonarqube:"
    agents:
      queue: "eks-dataservices-agent:ci"
      aws:account-id: 'awscloud.data-engineering.production'
    plugins:
      ssh://git@git.realestate.com.au/cide/sonar-buildkite-plugin#c791cba0a2387ace57452c44c6b459d4fbfecf83:
        projectKey: "api-template"
        projectname: "API Template"
        coverage_exclusions: "**/tests/**"

  - wait

  - label: "Build Dev :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Dev "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "master"

  - block: "Deploy to STAGING :kubernetes: Cluster!!!"
    branches: "master"

  - label: "Running tests in staging environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - wait

  - label: "Build Staging :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - block: "Deploy to Production :kubernetes: Cluster!!!"
    branches: "master"

  - label: "Running tests in production environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"
  
  - wait

  - label: "Build Production :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"