steps:
  - label: "Running tests in development environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent-dev'
    artifact_paths:
      - "coverage.xml"
      - "py-test-report.xml"
      - "pylint-report.parseable"
  
  - wait

  - label: "Sonar scan :sonarqube:"
    agents:
      queue: "eks-dataservices-agent-dev"
    plugins:
      ssh://git@git.realestate.com.au/cide/sonar-buildkite-plugin#7893f59e3cc5b62617ff30f85525902fd1e8024c:
        projectKey: "api-template"
        projectname: "API Template"
        coverage_exclusions: "**/tests/**"

  - wait

  - label: "Build Dev :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent-dev'
    branches: "master test-new-bk-agent"

  - wait

  - label: "Deploy to :kubernetes: Dev "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent-dev'
    branches: "master test-new-bk-agent"

  - block: "Deploy to STAGING :kubernetes: Cluster!!!"
    branches: "master test-new-bk-agent"

  - label: "Running tests in staging environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent-staging'
    branches: "master test-new-bk-agent"

  - wait

  - label: "Build Staging :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent-staging'
    branches: "master test-new-bk-agent"

  - wait

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent-staging'
    branches: "master test-new-bk-agent"

  - block: "Deploy to Production :kubernetes: Cluster!!!"
    branches: "master test-new-bk-agent"

  - label: "Running tests in production environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent-prod'
    branches: "master test-new-bk-agent"
  
  - wait

  - label: "Build Production :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent-prod'
    branches: "master test-new-bk-agent"

  - wait

  - label: "Deploy to :kubernetes: Production "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent-prod'
    branches: "master test-new-bk-agent"