steps:

  - label: "Build Dev :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "buildkite-integration"

  - block: "Deploy to DEV :kubernetes: Cluster!!!"

  - label: "Deploy to :kubernetes: Dev "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "buildkite-integration"

  - label: "Build Staging :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "buildkite-integration"

  - block: "Deploy to STAGING :kubernetes: Cluster!!!"

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "buildkite-integration"