steps:
  - label: "Running tests and lint in development environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    artifact_paths:
      - "coverage.xml"
      - "py-test-report.xml"
      - "pylint-report.parseable"
  
  - wait

  - label: "Build Dev :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Dev "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "DEV"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.development'
    branches: "master"

  - block: "Deploy to STAGING :kubernetes: Cluster!!!"
    branches: "master"

  - label: "Running tests and lint in staging environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - wait

  - label: "Build Staging :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "STAGING"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.staging'
    branches: "master"

  - block: "Deploy to Production :kubernetes: Cluster!!!"
    branches: "master"

  - label: "Running tests and lint in production environment"
    command: "auto/test"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"
  
  - wait

  - label: "Build Production :docker: image"
    command: "auto/build"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"

  - wait

  - label: "Deploy to :kubernetes: Staging "
    command: "auto/deploy"
    env:
      ENVIRONMENT: "PROD"
    agents:
      queue: 'eks-dataservices-agent:ci'
      aws:account-id: 'awscloud.data-engineering.production'
    branches: "master"