#!/usr/bin/env bash

set -euxo pipefail

cd "$(dirname $0)/.."

docker run --rm -w /source \
-v "$(pwd)":/source \
python:3.7-slim-buster \
sh -c "pip install -r requirements.txt \
&& pip install -U pytest coverage \
&& coverage run -m pytest tests && coverage xml"