#!/usr/bin/env bash

set -euxo pipefail

cd "$(dirname $0)/.."

pip install -r requirements.txt &&
    pip install -U pytest coverage &&
    coverage run -m pytest tests --junitxml=py-test-report.xml && coverage xml
