kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    department: {{ .Values.department }}
    app.kubernetes.io/name: {{ .Values.configMap.name }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}