apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    department: {{ .Values.department }}
    app.kubernetes.io/name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      department: {{ .Values.department }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        department: {{ .Values.department }}
    spec:
      {{- if and .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end  }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.buildNumber }}"
          env:
            {{- toYaml .Values.container.environments | nindent 12 }}
          ports:
            - containerPort: {{ .Values.container.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.healthCheckUrl }}
              port: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.container.healthCheckUrl }}
              port: {{ .Values.container.port }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          {{ if .Values.volumeMounts }}
          volumeMounts:
          {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
          {{- end }}
          {{- end }}
      {{ if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        secret:
          secretName: {{ .name }}
          defaultMode: {{ .defaultMode }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}