{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app: {{ .Chart.Name }}
    department: {{ .Values.department }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
{{- range $k, $v := .Values.ingress.hosts }}
  - host: {{ $v.host }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      {{- range $c, $d := $v.paths }}
      - path: {{ $d.path }}
        backend:
          serviceName: {{ $d.serviceName }}
          servicePort: {{ $d.servicePort }}
      {{- end }}
{{- end }}
{{- end }}

