{{- if .Values.secrets }}
{{- range $m, $n := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $n.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    department: {{ $.Values.department }}
    app.kubernetes.io/name: {{ $n.name }}
type: Opaque
data:
  {{- toYaml $n.data | nindent 2 }}
{{- end }}
{{- end }}


{{- if .Values.secretFiles }}
{{- range $k, $v := .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    department: {{ $.Values.department }}
    app.kubernetes.io/name: {{ $v.name }}
type: Opaque
{{- range $c, $d := $v.data }}
data:
  {{ $d.name }} : {{ $.Files.Get $d.path | b64enc | indent 2 }}
{{- end }}
{{- end }}
{{- end }}