{{- if and .Values.role .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    department: {{ .Values.department }}
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
{{- end  }}